#!/usr/bin/env python3
"""Independent reference implementation of the § 32a EStG income tax tariff.

This script exists to cross-check `casivell-tax`. It evaluates the statute the
obvious way — with arbitrary-precision decimals, transcribing each zone formula
as printed — whereas the engine clears the denominators and evaluates a single
integer quotient. The two derivations share only the statutory coefficients, so
agreement between them is evidence that the engine's algebra is right.

Consequently:

  * This script must never import from, or be generated by, the Rust engine.
    Doing so would turn the cross-check into a tautology.
  * The figures it prints are pasted into `crates/casivell-tax/src/tariff.rs`,
    test `the_integer_evaluation_agrees_with_an_independent_decimal_one`.
    If that test ever fails, exactly one of the two implementations is wrong, and
    which one is an open question until a human resolves it against the statute.

It also prints the errors the original project specification's tariff would have
produced, which is what motivated the rewrite. See docs/ROADMAP_ERRATA.md.

Sources
-------
§ 32a Abs. 1 EStG, versions for VZ 2025 (Art. 1 SteFeG) and from VZ 2026
(Art. 2 SteFeG), <https://www.gesetze-im-internet.de/estg/__32a.html>.

Usage
-----
    python3 docs/reference/generate_tariff_reference.py
"""

from __future__ import annotations

from decimal import Decimal as D
from decimal import getcontext

getcontext().prec = 50

# Sample points chosen to exercise every zone and both sides of each boundary.
SAMPLE_ZVE = [
    15_000, 20_000, 25_000, 30_000, 40_000,
    45_000, 60_000, 70_000, 100_000, 300_000, 400_000,
]


def tariff_2026(zve: int) -> D:
    """Return the tax under § 32a Abs. 1 EStG as in force from VZ 2026."""
    x = D(zve)
    if x <= 12_348:
        return D(0)
    if x <= 17_799:
        y = (x - 12_348) / 10_000
        return (D("914.51") * y + 1_400) * y
    if x <= 69_878:
        z = (x - 17_799) / 10_000
        return (D("173.10") * z + 2_397) * z + D("1034.87")
    if x <= 277_825:
        return D("0.42") * x - D("11135.63")
    return D("0.45") * x - D("19470.38")


def tariff_2025(zve: int) -> D:
    """Return the tax under § 32a Abs. 1 EStG as in force for VZ 2025."""
    x = D(zve)
    if x <= 12_096:
        return D(0)
    if x <= 17_443:
        y = (x - 12_096) / 10_000
        return (D("932.30") * y + 1_400) * y
    if x <= 68_480:
        z = (x - 17_443) / 10_000
        return (D("176.64") * z + 2_397) * z + D("1015.13")
    if x <= 277_825:
        return D("0.42") * x - D("10911.92")
    return D("0.45") * x - D("19246.67")


def tariff_as_originally_specified(zve: int) -> D:
    """Return the tax under the tariff written in the original specification.

    Retained solely to quantify the error it would have shipped. Every coefficient
    and every boundary below is wrong; see docs/ROADMAP_ERRATA.md for the
    side-by-side comparison. Do not use this for anything else.
    """
    x = D(zve)
    if x <= 12_096:
        return D(0)
    if x <= 17_643:
        y = (x - 12_096) / 10_000
        return (D("922.98") * y + 1_400) * y
    if x <= 28_397:
        z = (x - 17_643) / 10_000
        return (D("181.19") * z + 2_397) * z + 1_035
    if x <= 392_782:
        return D("0.42") * x - 10_397
    return D("0.45") * x - 22_228


def main() -> None:
    """Print the reference table and the original specification's error."""
    # § 32a Abs. 1 Satz 2: the resulting tax is truncated to whole euro.
    print("Reference values, individual assessment (Grundtarif).")
    print("Paste into casivell-tax::tariff::tests.\n")
    print(f"{'zvE':>10}  {'tax 2026':>10}  {'tax 2025':>10}")
    for zve in SAMPLE_ZVE:
        print(f"{zve:>10,}  {int(tariff_2026(zve)):>10,}  {int(tariff_2025(zve)):>10,}")

    print("\n\nError the original specification's tariff would have produced (vs 2026):\n")
    print(f"{'zvE':>10}  {'as specified':>13}  {'correct':>10}  {'error':>10}  {'error %':>9}")
    worst_abs = 0
    worst_pct = D(0)
    for zve in SAMPLE_ZVE:
        specified = int(tariff_as_originally_specified(zve))
        correct = int(tariff_2026(zve))
        error = specified - correct
        pct = (D(error) / D(correct) * 100) if correct else D(0)
        worst_abs = max(worst_abs, abs(error))
        worst_pct = max(worst_pct, abs(pct))
        print(f"{zve:>10,}  {specified:>13,}  {correct:>10,}  {error:>+10,}  {pct:>+8.1f}%")
    print(f"\nWorst absolute error: {worst_abs:,} EUR")
    print(f"Worst relative error: {worst_pct:.1f} %")


if __name__ == "__main__":
    main()
